Dex 823 password reset page
WildMeOrg/codex-frontend pull request #361
Opened 2022-05-26 22:28 UTC by Atticus29

2022-05-26 22:48 UTC, Atticus29 commented
Whoops. The missing photo. I don't know why it wasn't working:
<img width="1552" alt="Screen Shot 2022-05-26 at 3 26 57 PM" src="https://user-images.githubusercontent.com/2775448/170591857-6889a4d7-b52f-4bc6-b4c2-77ad48604b93.png">

2022-05-27 00:58 UTC, Emily-Ke approved these changes

2022-05-27 00:58 UTC, Emily-Ke commented on src/pages/auth/PasswordReset.jsx
> +          style={{ width: '100ﬁ' }}
Is `fi` a valid unit? It doesn't seem like it is being applied.

2022-05-27 06:54 UTC, brmscheiner requested changes
Some quick UI changes requested... 
<img width="240" alt="image" src="https://user-images.githubusercontent.com/9775178/170646807-9bc401ab-e616-44bb-8deb-9e20cf80bf6e.png">
Use type: password for the text so that you cannot see the password as it is typed.

Change the text "try again" to "resend email" and change the button from display='primary' to something less enticing (secondary or maybe panel, whatever looks better).

2022-05-27 21:26 UTC, brmscheiner approved these changes

2022-05-27 21:26 UTC, merged